// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApis.Models;

namespace WebApis.Migrations
{
    [DbContext(typeof(EmployesDBContex))]
    [Migration("20210530073101_CreateTable_Customers")]
    partial class CreateTable_Customers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApis.Models.Customers", b =>
                {
                    b.Property<int>("Customersid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomersFirstName");

                    b.Property<string>("CustomersLastName");

                    b.HasKey("Customersid");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("WebApis.Models.Employes", b =>
                {
                    b.Property<int>("employesid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("employesdesignation");

                    b.Property<string>("employesname");

                    b.Property<int>("employessalary");

                    b.HasKey("employesid");

                    b.ToTable("Employes");
                });
#pragma warning restore 612, 618
        }
    }
}
